/*
 */
package davidoliva_lab9p2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DAVIDANDRESOLIVAHERN
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        HiloFachaHora n = new HiloFachaHora(jLabelDarHora,jLabelDarFecha);
        n.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        JPInfoFecha = new javax.swing.JPanel();
        jLabelBienvenidos = new javax.swing.JLabel();
        jLabelFechadeHoy = new javax.swing.JLabel();
        jLabelDarHora = new javax.swing.JLabel();
        jLabelHoraActual = new javax.swing.JLabel();
        jLabelDarFecha = new javax.swing.JLabel();
        jPanelAzul = new javax.swing.JPanel();
        jButtonSubirArchivo = new javax.swing.JButton();
        jProgressBarSubiendoArchivo = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaArchivo = new javax.swing.JTextArea();
        jLabelArchivo = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPInfoFecha.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBienvenidos.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelBienvenidos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBienvenidos.setText("Bienvenidos");

        jLabelFechadeHoy.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelFechadeHoy.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFechadeHoy.setText("Fecha de Hoy:");

        jLabelDarHora.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabelDarHora.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDarHora.setText("jLabel6");

        jLabelHoraActual.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelHoraActual.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHoraActual.setText("Hora Actual:");

        jLabelDarFecha.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabelDarFecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDarFecha.setText("jLabel8");

        javax.swing.GroupLayout JPInfoFechaLayout = new javax.swing.GroupLayout(JPInfoFecha);
        JPInfoFecha.setLayout(JPInfoFechaLayout);
        JPInfoFechaLayout.setHorizontalGroup(
            JPInfoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInfoFechaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(JPInfoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDarFecha)
                    .addComponent(jLabelFechadeHoy)
                    .addComponent(jLabelBienvenidos)
                    .addComponent(jLabelHoraActual)
                    .addComponent(jLabelDarHora))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        JPInfoFechaLayout.setVerticalGroup(
            JPInfoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInfoFechaLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabelBienvenidos)
                .addGap(34, 34, 34)
                .addComponent(jLabelFechadeHoy)
                .addGap(37, 37, 37)
                .addComponent(jLabelDarFecha)
                .addGap(28, 28, 28)
                .addComponent(jLabelHoraActual)
                .addGap(38, 38, 38)
                .addComponent(jLabelDarHora)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        Base.add(JPInfoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        jPanelAzul.setBackground(new java.awt.Color(102, 102, 255));

        jButtonSubirArchivo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonSubirArchivo.setText("Subir Archivo");
        jButtonSubirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubirArchivoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel1.setText("Subiendo Archivo:");

        jTextAreaArchivo.setColumns(20);
        jTextAreaArchivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextAreaArchivo.setRows(5);
        jTextAreaArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaArchivoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaArchivo);

        jLabelArchivo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabelArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelArchivo.setText("Archivo");

        jButtonGuardar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Boroa Cloud");

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addGroup(jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAzulLayout.createSequentialGroup()
                        .addGroup(jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAzulLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jButtonSubirArchivo)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                    .addComponent(jProgressBarSubiendoArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelAzulLayout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jButtonGuardar)))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(jPanelAzulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonSubirArchivo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarSubiendoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabelArchivo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        Base.add(jPanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubirArchivoMouseClicked
        AbrirArchivo();
    }//GEN-LAST:event_jButtonSubirArchivoMouseClicked

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        CrearArchivo();
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jTextAreaArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaArchivoMouseClicked
        
    }//GEN-LAST:event_jTextAreaArchivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel JPInfoFecha;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSubirArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelArchivo;
    private javax.swing.JLabel jLabelBienvenidos;
    private javax.swing.JLabel jLabelDarFecha;
    private javax.swing.JLabel jLabelDarHora;
    private javax.swing.JLabel jLabelFechadeHoy;
    private javax.swing.JLabel jLabelHoraActual;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JProgressBar jProgressBarSubiendoArchivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaArchivo;
    // End of variables declaration//GEN-END:variables
    public void AbrirArchivo() {
        File fichero = null;
        BufferedReader br = null;
        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                FileReader fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                String n = "";
                while ((linea = br.readLine()) != null) {
                    n += linea + "\n";
                }
               HiloProgesoArchivo hilo=new HiloProgesoArchivo(jProgressBarSubiendoArchivo,jTextAreaArchivo,n);
               hilo.start();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {

            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace(); 
            }
        }
    }
        
    public void CrearArchivo() {
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
                try {
                    fw = new FileWriter("./Archivo");
                    bw = new BufferedWriter(fw);
                    bw.write(jTextAreaArchivo.getText());
                    bw.newLine();
                    bw.flush();
                } catch (IOException ex) {
                    ex.printStackTrace(); // Mejor manejo de excepciones
                } finally {
                    if (bw != null) {
                        try {
                            bw.close();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                    }
                    if (fw != null) {
                        try {
                            fw.close();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                    }
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
